version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing
    ports:
      - '5432:5432'
